#!/usr/bin/env bash
# This script transfers a file to a specified server using SCP

if [ $# -ne 4 ]; then
	  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Ensure that the SSH private key file exists
if [ ! -f "$PATH_TO_SSH_KEY" ]; then
	  echo "Error: SSH key file '$PATH_TO_SSH_KEY' does not exist."
	    exit 1
fi

# Ensure that the file to be transferred exists
if [ ! -f "$PATH_TO_FILE" ]; then
	  echo "Error: File '$PATH_TO_FILE' to transfer does not exist."
	    exit 1
fi

# Execute SCP command
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~

