#!/usr/bin/env bash
# This script transfers a file from user to server

# Check if exactly 4 parameters were passed
if [ $# -ne 4 ]; then
	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	        exit 1
fi

# Execute SCP with specified options
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
if [ $? -eq 0 ]; then
	    echo "File transfer successful."
    else
	        echo "Error during file transfer."
		    exit 1
fi
