#!/usr/bin/env bash

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
