#!/usr/bin/env bash

# shellcheck disable=SC2009

# Use ps command to display lines containing the word "bash"
# Then using grep to filter out the lines containing the script name
# Use grep again to filter out the line containing the grep command itself

ps aux | grep bash 
