#!/bin/bash

# Use pkill to send SIGINT signal to the process
pkill -INT -f "4-to_infinity_and_beyond"
#!/bin/bash

# Use pkill to send SIGINT signal to the process
pkill -INT -f "4-to_infinity_and_beyond"

