#!/bin/bash

trap 'echo "I am invincible!!!"' SIGTERM

if [[ "$0" == *"7-highlander"* ]]; then
	while true; do
		echo "To infinity and beyond"
		sleep 2
	done
else
	pkill -SIGTERM -f "7-highlander"
fi
