#!/usr/bin/env bash

#Displaying "Infinity and beyond" continually
# Apply sleep 2 after each iteration
# Display "I am invincible after each iteration"

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
