#!/usr/bin/env bash
#This script displays the content of the /etc/passwd file

filename="/etc/passwd"

while IFS=: read -r username _ userid _ _ home_dir _; do
	    echo "$username:$userid:$home_dir"
    done < "$filename"
