#!/usr/bin/env bash
#This script tells a story based on the content of /etc/passwd

filename="/etc/passwd"

while IFS=: read -r username _ userid groupid _ home_dir shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_dir, and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < "$filename"
