#!/usr/bin/env bash
# This script configures the ufw firewall to block all incoming traffic

echo -e "Updating\n"

sudo apt-get update

echo -e "Installing UFW\n"

sudo apt-get install -y ufw

echo -e "configuring UFW...\n"

# Allowing Outgoing and Denying Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allowing ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enabling Fire Wall
sudo ufw enable

echo -e "Process Completed.\n" 
