#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	        exit 1
fi

# Assign parameters to variables
FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer file to the server using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$SERVER_IP":~/ 

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
	    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
    else
	        echo "Failed to transfer file to $USERNAME@$SERVER_IP:~/"
		    exit 1
fi

